# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p-8rw8CWMFwH6sLClZ7C5vjhnMQQNOzP
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt

# --------------------------------------------------
# PAGE CONFIG
# --------------------------------------------------
st.set_page_config(
    page_title="College Football Defensive Analytics",
    page_icon="🏈",
    layout="wide"
)

# --------------------------------------------------
# LOAD DATA
# --------------------------------------------------
@st.cache_data
def load_data():
    url = "https://raw.githubusercontent.com/IndumathyPrem/Defensive-Football-Analysis/refs/heads/main/Raw-Data-cfb-defensive-box-scores.csv"
    return pd.read_csv(url)

df = load_data()

# --------------------------------------------------
# SIDEBAR
# --------------------------------------------------
st.sidebar.title("🏈 Filters")

season = st.sidebar.multiselect(
    "Season",
    sorted(df["season"].dropna().unique()),
    default=sorted(df["season"].dropna().unique())
)

team = st.sidebar.multiselect(
    "Team",
    sorted(df["team"].dropna().unique()),
    default=sorted(df["team"].dropna().unique())
)

filtered_df = df[
    (df["season"].isin(season)) &
    (df["team"].isin(team))
]

# --------------------------------------------------
# HEADER
# --------------------------------------------------
st.title("🏈 Analysis of Defensive Statistics in College Football")
st.markdown(
    "Interactive analytics dashboard built using **Python, Pandas, Seaborn and Streamlit**."
)

# --------------------------------------------------
# KPI SECTION
# --------------------------------------------------
c1,c2,c3,c4,c5,c6 = st.columns(6)

c1.metric("Total Records", f"{len(filtered_df):,}")

c2.metric(
    "Avg Tackles",
    round(filtered_df["tackles_total"].mean(),2)
)

c3.metric(
    "Max Tackles",
    int(filtered_df["tackles_total"].max())
)

c4.metric(
    "Total Sacks",
    int(filtered_df["sacks"].sum())
)

c5.metric(
    "Total INT",
    int(filtered_df["int"].sum(skipna=True))
)

c6.metric(
    "Seasons",
    filtered_df["season"].nunique()
)

st.divider()

# --------------------------------------------------
# PAGE 1 VISUALS
# --------------------------------------------------

col1,col2 = st.columns(2)

with col1:

    fig = px.pie(
        filtered_df,
        names="home_away",
        hole=0.5,
        title="Home vs Away Games"
    )

    st.plotly_chart(fig,use_container_width=True)

with col2:

    top_teams = (
        filtered_df
        .groupby("team")["tackles_total"]
        .mean()
        .sort_values(ascending=False)
        .head(10)
        .reset_index()
    )

    fig = px.bar(
        top_teams,
        x="tackles_total",
        y="team",
        orientation="h",
        title="Top 10 Teams by Average Tackles"
    )

    st.plotly_chart(fig,use_container_width=True)

# --------------------------------------------------
# RESULT ANALYSIS
# --------------------------------------------------

avg_result = (
    filtered_df
    .groupby("result")["tackles_total"]
    .mean()
    .reset_index()
)

fig = px.bar(
    avg_result,
    x="result",
    y="tackles_total",
    title="Average Tackles by Game Result"
)

st.plotly_chart(fig,use_container_width=True)

# --------------------------------------------------
# SEASON TREND
# --------------------------------------------------

trend = (
    filtered_df
    .groupby("season")["tackles_total"]
    .mean()
    .reset_index()
)

fig = px.line(
    trend,
    x="season",
    y="tackles_total",
    markers=True,
    title="Defensive Performance Trend by Season"
)

st.plotly_chart(fig,use_container_width=True)

# --------------------------------------------------
# CORRELATION HEATMAP
# --------------------------------------------------

st.subheader("Correlation Heatmap")

corr_cols = [
    "tackles_total",
    "tackles_solo",
    "sacks",
    "tfl",
    "pd"
]

corr = filtered_df[corr_cols].corr()

fig, ax = plt.subplots(figsize=(8,5))

sns.heatmap(
    corr,
    annot=True,
    cmap="coolwarm",
    fmt=".2f",
    ax=ax
)

st.pyplot(fig)

# --------------------------------------------------
# SCATTER PLOT
# --------------------------------------------------

fig = px.scatter(
    filtered_df,
    x="tackles_solo",
    y="tackles_total",
    color="result",
    title="Total Tackles vs Solo Tackles"
)

st.plotly_chart(fig,use_container_width=True)

# --------------------------------------------------
# INSIGHTS
# --------------------------------------------------

st.header("📌 Key Insights")

st.success("""
• Dataset contains over 30,000 defensive records.

• Players average approximately 2 tackles per game.

• Home and away games are nearly balanced.

• Total tackles and solo tackles show a strong positive relationship.

• Top teams consistently outperform the overall average.
""")

# --------------------------------------------------
# RECOMMENDATIONS
# --------------------------------------------------

st.header("🎯 Recommendations")

st.info("""
• Focus on tackling consistency and efficiency.

• Monitor sacks and tackles-for-loss together.

• Evaluate players using multiple defensive metrics.

• Track season-over-season performance improvements.
""")

# --------------------------------------------------
# FINAL STORY
# --------------------------------------------------

st.header("📖 Dashboard Story")

st.write("""
This dashboard analyzes defensive performance in college football.
The findings reveal that tackling remains the foundation of defensive success,
while sacks, interceptions, and tackles-for-loss provide additional impact.
The balanced distribution of home and away games allows fair comparisons,
and trend analysis highlights how defensive activity changes across seasons.
""")